### ISSUE TITLE
Intel PT error

### ISSUE THREAD

**Issue by Mizari** [googleprojectzero/winafl#296]
Hello!
I'm getting invalid parameter (getlasterror == 0x57) while trying to fuzz with IPT.
The error happens here https://github.com/googleprojectzero/winafl/blob/master/winaflpt.c#L1455
Debugging showed me, that device is opened correctly at https://github.com/ionescu007/winipt/blob/master/libipt/win32.c#L267
but DeviceIoControl fails at https://github.com/ionescu007/winipt/blob/master/libipt/win32.c#L276.

I am running under admin privileges
Windows version 1909, 18363.1256
Earlier fuzzing was running OK, did something change?
I tried old version and new, same thing happens

**Comment by ifratric** [comment]
Hmm not sure why it fails on 1909, but I know on later versions (2004 and above) there was an issue that was fixed in WinIPT in https://github.com/ionescu007/winipt/pull/10. Note also that WinIPT version in WinAFL repo is out-of-date and should be updated.

**Comment by Mizari** [comment]
Using current winipt and libipt submodules did not solve the ipt tracing error

**Comment by ifratric** [comment]
If you get WinIPT from https://github.com/ionescu007/winipt and build and run it standalone (without WinAFL), do you still get the same error?

**Comment by Mizari** [comment]
Yes, I got it there, didnt help. BUT
Turns out the trace_size I gave is too big (0x1000000), the exact same trace_size earlier was fine. No idea what changed
